name: pagina_servicios_computo
version: 1.0.0+1
description: Aplicación web Flutter de servicios de mantenimiento, reparación y asesoría en equipos de cómputo para Bogotá.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
